version: 2
updates:
- package-ecosystem: npm
  directory: "/desktop"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
- package-ecosystem: cargo
  directory: "/packer"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
