name:                bump
version:             0.1.0.1

dependencies:
  - base >= 4.7 && < 5
  - turtle
  - system-filepath
  - foldl
  - text

executables:
  bump:
    source-dirs:      .
    main:             bump.hs
    ghc-options:      -O2 -optl-s
    ld-options:       -static -fuse-ld=gold
