name: Validate Podspecs
on:
  push:
    #   paths:
    #     - "iOS/**"
    #     - "xplat/**"
    #     - "Flipper.podspec"
    #     - "FlipperKit.podspec"
    # pull_request:
    #   paths:
    #     - "iOS/**"
    #     - "xplat/**"
    #     - "Flipper.podspec"
    #     - "FlipperKit.podspec"
    branches:
      - "pod-lib-lint-subspecs"
jobs:
  lint-flipperkit_fbdefines_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FBDefines
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FBDefines --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_core_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/Core
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/Core --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_cppbridge_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/CppBridge
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/CppBridge --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_dynamic_convert_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FBCxxFollyDynamicConvert
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FBCxxFollyDynamicConvert --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_port_forwarding_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FKPortForwarding
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FKPortForwarding --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_layout_highlight_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitHighlightOverlay
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitHighlightOverlay --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_layout_text_searchable_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitLayoutTextSearchable
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitLayoutTextSearchable --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_layout_helpers_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitLayoutHelpers
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitLayoutHelpers --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_layout_ios_descriptors_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitLayoutIOSDescriptors
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitLayoutIOSDescriptors --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_layout_plugin_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitLayoutPlugin
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitLayoutPlugin --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_layout_ck_plugin_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitLayoutComponentKitSupport
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitLayoutComponentKitSupport --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_network_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitNetworkPlugin
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitNetworkPlugin --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_skiosnetwork_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/SKIOSNetworkPlugin
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/SKIOSNetworkPlugin --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_user_default_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitUserDefaultsPlugin
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitUserDefaultsPlugin --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_example_plugin_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitExamplePlugin
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitExamplePlugin --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_react_plugin_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitReactPlugin
        run: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitReactPlugin --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipper_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint Flipper
        run: pod lib lint Flipper.podspec --use-libraries --allow-warnings --verbose
