# This is a basic workflow to help you get started with Actions

name: CI
on: [push, pull_request]

jobs:
  lint-flipperkit_pod:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install Dependences
      run: pod repo update
      
    - name: Lint FlipperKit
      run: pod spec lint FlipperKit.podspec --use-libraries --allow-warnings --verbose --skip-import-validation
    
  lint-flipper_pod:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependences
      run: pod repo update
    - name: Lint Flipper
      run: pod spec lint Flipper.podspec --use-libraries --allow-warnings --verbose
      
      
