name: Validate Podspecs
on: [push, pull_request]

jobs:
  lint-flipperkit_pod:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update

      - name: Lint FlipperKit
        run: pod spec lint FlipperKit.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipper_pod:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint Flipper
        run: pod spec lint Flipper.podspec --use-libraries --allow-warnings --verbose

  lint-flipper_doubleconversion_pod:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint DoubleConversion
        run: cd iOS/Podspecs && pod spec lint Flipper-DoubleConversion.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipper_folly_pod:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint Folly
        run: cd iOS/Podspecs && pod spec lint Flipper-Folly.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipper_glog_pod:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint Glog
        run: cd iOS/Podspecs && pod spec lint Flipper-Glog.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipper_peertalk_pod:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint Peertalk
        run: cd iOS/Podspecs && pod spec lint Flipper-PeerTalk.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipper_rsocket_pod:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependences
        run: pod repo update
      - name: Lint RSocket
        run: cd iOS/Podspecs && pod spec lint Flipper-RSocket.podspec --use-libraries --allow-warnings --verbose --skip-import-validation
