# This is a basic workflow to help you get started with Actions

name: Build iOS Sample/Tutorial Swift and Objective-C apps

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:       
  build-sample-objc:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: iOS/Sample
        
    steps:
    - uses: actions/checkout@v2      
    - name: Install dependencies
      run: pod install --repo-update
    - name: Build Sample app
      run: |
        IPHONESIMULATOR=$(xcodebuild -showsdks | grep -o "iphonesimulator[0-9]\\+\\.[0-9]\\+$") && echo $IPHONESIMULATOR
        xcodebuild build -workspace Sample.xcworkspace -scheme Sample -sdk $IPHONESIMULATOR
        
  build-sample-swift:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: iOS/SampleSwift
        
    steps:
    - uses: actions/checkout@v2      
    - name: Install dependencies
      run: pod install --repo-update
    - name: Build SampleSwift app
      run: |
        IPHONESIMULATOR=$(xcodebuild -showsdks | grep -o "iphonesimulator[0-9]\\+\\.[0-9]\\+$") && echo $IPHONESIMULATOR
        xcodebuild build -workspace SampleSwift.xcworkspace -scheme SampleSwift -sdk $IPHONESIMULATOR
        
  build-tutorial:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: iOS/Tutorial
        
    steps:
    - uses: actions/checkout@v2      
    - name: Install dependencies
      run: pod install --repo-update
    - name: Build Tutorial app
      run: |
        IPHONESIMULATOR=$(xcodebuild -showsdks | grep -o "iphonesimulator[0-9]\\+\\.[0-9]\\+$") && echo $IPHONESIMULATOR
        xcodebuild build -workspace Tutorial.xcworkspace -scheme Tutorial -sdk $IPHONESIMULATOR

