name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install
      working-directory: pkg
      run: yarn
    - name: lint
      working-directory: pkg
      run: yarn lint
    - name: test
      working-directory: pkg
      run: yarn test
    - name: run
      working-directory: pkg
      run: bin/run
