name: Packer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test
        run: cd packer && cargo test
      - name: Format
        run: cd packer && cargo fmt -- --check
      - name: Lint
        run: cd packer && cargo clippy -- -Dwarnings
