name: Packer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Test
        uses: icepuma/rust-action@1.44.0
        with:
          args: cd packer && cargo test
      - name: Format
        uses: icepuma/rust-action@1.44.0
        continue-on-error: true
        with:
          args: cd packer && cargo fmt -- --check
      - name: Lint
        uses: icepuma/rust-action@1.44.0
        continue-on-error: true
        with:
          args: cd packer && cargo clippy -- -Dwarnings
