name: Packer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@1.44.0
        working-directory: packer
        with:
          args: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test
