name: Publish Pods
on:
  push:
      branches:
      - publish-pods-gh

jobs:
  publish_flipper_pod:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependences
      run: pod repo update

    - name: Pod Version
      run: pod --version

    - name: Push Flipper
      run: pod trunk push Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

  publish_flipperkit_pod:
    needs: publish_flipper_pod
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies

      run: pod repo update

    - name: Pod Version
      run: pod --version

    - name: Push FlipperKit
      run: |
        # Retry publishing FlipperKit 5 times. Putting this hack unless we have cocoapods 1.10. More information related to the bug https://github.com/CocoaPods/CocoaPods/issues/9502#issuecomment-579486258
        for i in {1..5}; do pod trunk push FlipperKit.podspec --use-libraries --allow-warnings --verbose --skip-import-validation && break || sleep 20; done
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

  commit_podfile_lock:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: iOS

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: pod repo update

    - name: Pod Version
      run: pod --version

    - name: Update Sample's Podfile.lock
      run: |
          cd Sample/
          pod update
          ls

    - name: Update SampleSwift's Podfile.lock
      run: |
          cd SampleSwift/
          pod update
          ls

    - name: Update Tutorial's Podfile.lock
      run: |
          cd Tutorial/
          pod update
          ls

    - name: Add and Commit the files
      uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: '*/Podfile.lock'

        # The name of the user that will be displayed as the author of the commit
        # Default: author of the commit that triggered the run
        author_name: My GitHub Actions Bot

        # The email of the user that will be displayed as the author of the commit
        # Default: author of the commit that triggered the run
        author_email: my-github-actions-bot@example.org

        # The local path to the directory where your repository is located. You should use actions/checkout first to set it up
        # Default: '.'
        cwd: '.'

        # Whether to use the --force option on `git add`, in order to bypass eventual gitignores
        # Default: false
        force: false

        # The message for the commit
        # Default: 'Commit from GitHub Actions'
        message: 'Automated Commit: Update Podfile.lock'

        # Name of the branch to use, if different from the one that triggered the workflow
        # Default: the branch that triggered the workflow (from GITHUB_REF)
        ref: 'update-podfile-lock'
      env:
        # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
