name: Publish Pods
on:
  push:
    branches:
      - gh-automatic-podfile-update

jobs:
  publish_flipper_pod:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependences
      run: pod repo update

    - name: Pod Version
      run: pod --version

    - name: Push Flipper
      run: pod trunk push Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

  publish_flipperkit_pod:
    needs: publish_flipper_pod
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependences
      run: pod repo update

    - name: Pod Version
      run: pod --version

    - name: Push FlipperKit
      run: |
        # Retry publishing FlipperKit 5 times. Putting this hack unless we have cocoapods 1.10. More information related to the bug https://github.com/CocoaPods/CocoaPods/issues/9502#issuecomment-579486258
        for i in {1..5}; do pod trunk push FlipperKit.podspec --use-libraries --allow-warnings --verbose --skip-import-validation && break || sleep 20; done
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

  commit_podfile_lock:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: iOS

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: pod repo update

    - name: Pod Version
      run: pod --version

    # - name: Update Sample's Podfile.lock
    #   run: |
    #       cd Sample/
    #       pod update
    #       ls
    # - name: Update SampleSwift's Podfile.lock
    #   run: |
    #       cd SampleSwift/
    #       pod update
    #       ls
    - name: Update Tutorial's Podfile.lock
      run: |
          cd Tutorial/
          pod update
          ls
    - name: Git status
      run: |
          git status
    - name: Git diff
      run: |
          git diff
    - name: Git branch
      run: |
          git branch
    - name: Git remote
      run: |
          git remote -v
    - name: Remove Pods
      run: rm -rf iOS/Tutorial/Pods
    - name: Pull bot-update-podfile-lock-DO-NOT-USE
      run: git pull origin bot-update-podfile-lock-DO-NOT-USE
    - name: Add and Commit the files
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Pritesh Nandgaonkar
        author_email: pncooldude91@gmail.com
        force: true
        add: '.'
        cwd: '.'
        message: 'Automated Commit: Update Podfile.lock'
        ref: bot-update-podfile-lock-DO-NOT-USE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
